name: Python Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Specify your Python version
      - name: Install dependencies
        run: |
          pip install flake8 pylint black
      - name: Run Flake8
        run: flake8 .
      - name: Run Pylint
        run: pylint .
      - name: Run Black (check only)
        run: black --check .